chromatic_scale = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']
modes_diatonic = ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Myxolodian', 'Aoelian', 'Locrian']
chord_type = ['Major', 'Minor', 'Diminished', 'Augmented']
chord_type_abbr = ['maj', 'min', 'dim', 'aug']
diatonic_intervals = ['W','W','H','W','W','W','H']
harmonic_minor_intervals = ['W','H','W','W','H','WH','H']
modes_harmonic_minor =['Harmonic Minor', 'Locrian', 'Ionian', 'Dorian', 'Phrygian Dominant', 'Lydian', 'Ultralocrian']